version: '3.9'
services:
  web:
    image: tautiz/web4study:latest
    volumes:
      - ./laravel_failai:/var/www/html/
    user: web:web
    ports:
      - "80:80"
    environment:
      PHP_IDE_CONFIG: 'serverName=laravel.local'
      APACHE_SERVER_NAME: laravel.local
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      APACHE_RUN_USER: web
      APACHE_RUN_GROUP: web

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

  mailpit:
      image: axllent/mailpit:latest
      ports:
        - "8025:8025"
        - "1025:1025"

volumes:
  myapp:
    external: false
