version: '3.3'
services:
  web:
    image: tautiz/web4study
    volumes:
      - ./laravel_failai:/var/www/html/
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: laravel.local
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`shop.lt`)"
      - "traefik.http.routers.web.entrypoints=web"
    networks:
      - traefik-gateway

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    networks:
      - traefik-gateway
    labels:
        - "traefik.enable=false"

volumes:
  myapp:
    external: false

networks:
  traefik-gateway:
    external: true