version: '3.9'
services:
  web:
    image: tautiz/web4study:latest
    volumes:
      - ./laravel_failai:/var/www/html/
      - ./.zshrc-alias:/root/.zshrc-alias:ro
    user: web:web
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: laravel.local
      APPLICATION_ENV: development
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      APACHE_RUN_USER: web
      APACHE_RUN_GROUP: web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`shop.lt`)"
      - "traefik.http.routers.web.entrypoints=web"
    networks:
      - traefik-gateway

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    networks:
      - traefik-gateway
    labels:
        - "traefik.enable=false"

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main.rule=Host(`hog.com`)"
    networks:
      - traefik-gateway

  node:
    image: "node:14.15.4-alpine"
    user: "node"
    working_dir: /var/www/html
    environment:
      - NODE_ENV=development
    volumes:
      - ./laravel_failai:/var/www/html/
    command: sh -c "npm run dev"

volumes:
  myapp:
    external: false

networks:
  traefik-gateway:
    external: true